import Aside from "@/components/Aside";
import Header from "@/components/Header";
import Main from "@/components/Main";
import { Box, Flex } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>codeisneverodd</title>
        <meta
          name="description"
          content="Generated by nextjs-chakra-template"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h="100vh">
        <Header />

        <Flex
          w="full"
          direction={{ sm: "column-reverse", md: "row" }}
          pt="20px"
        >
          <Main />
          <Aside />
        </Flex>
      </Box>
    </>
  );
}
